---
- name: create compose file directory
  file:
    path: "{{ item }}"
    state: directory
    owner: pi
    group: pi
    mode: 0774
  with_items:
    - "{{ monitoring_conf_dir }}"

- name: create compose config file
  copy:
    src: "compose/{{item}}"
    dest: "{{ monitoring_conf_dir }}/{{ item }}"
    owner: pi
    group: pi
    mode: 0774
  with_items:
    - "docker-compose.yml"
  notify:
    - restart monitoring service

- name: create systemd compose file
  copy:
    src: "compose/{{item}}"
    dest: "{{ systemd_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0777
  with_items:
    - "docker-monitoring.service"
  notify:
    - start monitoring service
