version: "3.3"

services:
  prometheus:
    image: prom/prometheus:v2.14.0
    container_name: prometheus
    user: root
    volumes:
      - /etc/prometheus/:/etc/prometheus/
      - /var/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=1000d"
      - "--storage.tsdb.retention.size=24GB"
      - "--web.enable-lifecycle"
    restart: always
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"

  pushgateway:
    # only master supports arm
    image: prom/pushgateway:master
    container_name: pushgateway
    restart: always
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"

  node_exporter:
    image: prom/node-exporter:v0.18.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    restart: always
    network_mode: host

  grafana:
    image: grafana/grafana:6.5.0
    user: root
    container_name: grafana
    volumes:
      - /var/grafana/data:/var/lib/grafana
      - /etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /var/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"
